name: build web embed

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:

jobs:
  build:
    uses: baladithyab/web-embed-workflows/.github/workflows/static-passthrough.yml@main
    with:
      manifest: web.codeseys.json
      source-dir: '.'
    secrets: inherit
    permissions:
      contents: write
      pull-requests: write
